Add controllers
KamperClout/java-shareit pull request #1
Opened 2023-09-09 19:45 UTC by KamperClout

2023-09-11 07:49 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть пара замечаний, которые необходимо исправить!

Желаю удачи!

2023-09-11 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>   */
Такие комментарии не стоит оставлять, если функционал уже реализован.
Это противоречит в том, числе принципу KISS

https://en.wikipedia.org/wiki/KISS_principle

2023-09-11 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +    public Map<Long, Item> items = new HashMap<>();
Почему `public`, такие коллекции должны быть инкапсулированы в класс, скрыты от модификации напрямую и доступны только через предоставляемые методы

2023-09-11 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +                    .filter(item -> item.getName().toLowerCase().contains(text) ||
А текст не надо приводить к нижнему регистру?
Или ты в другом месте это делаешь?

2023-09-11 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        if ((item.getName().isEmpty()) || (item.getDescription().isEmpty()) || (item.getAvailable() == null)) {
Зачем каждую проверку оборачивать в дополнительные скобки?

2023-09-11 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        ItemDto newItemDto = null;
1) не ясно зачем заводить для этого переменную
2) не очень понятно, почему при отсутствии пользователя не выбрасывается исключение

2023-09-11 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return newItemDto;
Писал про это выше

2023-09-11 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/mapper/Mapper.java
> +public class Mapper {
https://www.baeldung.com/java-helper-vs-utility-classes

2023-09-11 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +        } else {
Если инвертировать условный оператор `else` будет не нужен, и сможем сократить уровень вложенности

2023-09-11 07:49 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +        } else {
Инвертируя условный оператор можно сократить уровень вложенности

2023-09-11 18:46 UTC, KamperClout commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +                    .filter(item -> item.getName().toLowerCase().contains(text) ||
в сервисе привожу его к нижнему регистру

2023-09-11 18:46 UTC, KamperClout commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +    public Map<Long, Item> items = new HashMap<>();
все исправил!

2023-09-11 18:47 UTC, KamperClout commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>   */
убрал!

2023-09-11 18:48 UTC, KamperClout commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        if ((item.getName().isEmpty()) || (item.getDescription().isEmpty()) || (item.getAvailable() == null)) {
отделил для читаемости)) Думал красивее будет смотреться...

2023-09-11 19:47 UTC, KamperClout commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        ItemDto newItemDto = null;
1.Исправил
2. Тоже исправил, но есть небольшой вопрос, все же путаюсь немного. При отсутствии пользователя исключение выбрасывается при вызове метода getUserById, так вот, по сути я тут глупо поступил, потому что до проверки на null не дойдет программа, так как выбросится исключение на этом методе. Проверка на отсутствие пользователя и выброс исключения проводится в InMemoryUserStorage, поэтому немного переделал в ItemService методы создания и обновления пользователя с учетом выброса исключения. Не знаю, верно это или нет, просто как я понимаю логику в контроллерах прописывать нежелательно. А так вроде получается что исключение будет выбрасываться. Не знаю правильно ли я все понял))

2023-09-11 19:52 UTC, KamperClout commented on src/main/java/ru/practicum/shareit/mapper/Mapper.java
> +public class Mapper {
все понял, спасибо!))

2023-09-11 20:48 UTC, KamperClout commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
> +        } else {
переделал

2023-09-12 07:01 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        ItemDto newItemDto = null;
Да, но бывают такие случаи, когда изначально была предусмотрена какая-то логика (например, выбрасывание исключение в `InMemoryUserStorage`), а потом контракты изменились, перешли к другому способу хранения данных и забыли там выбрасывать исключение.

Для таких случаев не лишним будет выбрасывание исключения в том случае, в котором я описал, чтобы наш код продолжал работать корректно (или хотя бы пользователь не получал какой-то неадекватный результат)

2023-09-12 07:03 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2023-09-12 07:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private ItemService itemService;
Здесь можно добавить модификатор `final`

2023-09-12 07:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private UserService userService;
Можно добавить модификаторы `final`

2023-09-14 19:44 UTC, merged