Add Bookings
KamperClout/java-shareit pull request #2
Opened 2023-09-28 07:47 UTC by KamperClout

2023-09-30 07:29 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые надо исправить!

Желаю удачи!

2023-09-30 07:29 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        } else {
1. `else` не нужен, так как выше у тебя конструкция if-return
2. Может выбрасывать исключение, а не возвращать `null`
3. Для всех методов ниже замечания аналогичные

2023-09-30 07:29 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +                    .allMatch(u -> u.getId().equals(userDto.getId()))) {
1. Зачем в первом условии нужны лишние скобки?
2. Зачем нам два условных оператора, если их можно объединить в один?
3. Если инвертировать наш условный оператор, то можно избавиться от ветки `else` и сократить цикломатическую сложность кода и уровень вложенности нашего кода 

https://en.wikipedia.org/wiki/Cyclomatic_complexity
https://en.wikipedia.org/wiki/Nesting_(computing)

2023-09-30 07:29 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +@Component
Здесь больше подойдет 
https://www.baeldung.com/java-helper-vs-utility-classes

2023-09-30 07:29 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                .reduce((a, b) -> b).orElse(null));
даже в лямбда-функциях стоит использовать нормальные имена переменных, а не однобуквенники

2023-09-30 07:29 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        } else {
Можно инвертировать условный оператор

2023-09-30 07:29 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +            text = text.toLowerCase();
Можно это не сохранять в переменную `text`, а сразу передавать в метод

2023-09-30 07:29 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    private final ItemService itemService;
https://softwareengineering.stackexchange.com/questions/414448/is-it-an-anti-pattern-to-have-service-to-service-dependency-in-the-layered-archi

Тут написано почему не стоит делать в классах зависимости одного уровня. Как у тебя сервис зависит от других сервисов

2023-09-30 07:29 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +            } else {
Инвертировать условие и сократить уровень вложенности

2023-09-30 07:29 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +            } else {
`else` не нужен

2023-09-30 07:29 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        } else {
`else` не нужен

2023-10-01 20:56 UTC, KamperClout commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        } else {
Исправил!

2023-10-01 21:27 UTC, KamperClout commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +                    .allMatch(u -> u.getId().equals(userDto.getId()))) {
все исправил, понял, что из за ограничения в бд по уникальности email можно гораздо проще)

2023-10-01 21:29 UTC, KamperClout commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    private final ItemService itemService;
Все исправил, сделал отдельный сервис оркестратор, дабы избежать зависимостей одного уровня

2023-10-01 21:36 UTC, KamperClout commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +@Component
Исправил!

2023-10-01 22:05 UTC, KamperClout commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +                .reduce((a, b) -> b).orElse(null));
исправил!

2023-10-01 22:08 UTC, KamperClout commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        } else {
Исправил

2023-10-01 22:10 UTC, KamperClout commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +            text = text.toLowerCase();
Выполнено!

2023-10-01 23:03 UTC, KamperClout commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +            } else {
Понял. Исправил

2023-10-01 23:03 UTC, KamperClout commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +            } else {
убрал

2023-10-01 23:03 UTC, KamperClout commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        } else {
аналогично убрал

2023-10-02 08:41 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2023-10-03 16:22 UTC, merged