commit 16 sprint #1: add docker
KamperClout/java-shareit pull request #4
Opened 2023-11-16 21:51 UTC by KamperClout

2023-11-17 17:58 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть пара замечаний, которые необходимо исправить!

Желаю удачи!

2023-11-17 17:58 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                             @RequestParam(required = false, defaultValue = "20") Integer size) {
1. Нет необходимости использовать `required = false` и `defaultValue`, так как `defaultValue` уже подразумевает выставленным этот параметр, это указано в документации.
2. Почему здесь ты указываешь `defaultValue` для `size`, а в `ItemRequestController` нет. Хотелось бы какой-нибудь универсальности :)

2023-11-17 17:58 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                           @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
Строки стоит вынести в константы

2023-11-17 17:58 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                  @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
Где-то используешь `PostiveOrZero`, где-то `Min(1)`, лучше это все унифицировать и выбрать что-то одно

2023-11-17 17:58 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                              @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
Если `name` совпадает с названием переменной, то в нем нет необходимости

2023-11-18 21:25 UTC, KamperClout commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                              @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
Исправил

2023-11-18 21:25 UTC, KamperClout commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                  @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
Все исправил

2023-11-18 21:25 UTC, KamperClout commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                           @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
Сделано

2023-11-18 21:26 UTC, KamperClout commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                  @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
Min использовал исключительно для айдишников, а позитив для постраничных выводов, поэтому так делал, но все исправил

2023-11-19 08:29 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи с дипломным проектом!

2024-01-06 15:21 UTC, merged